import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import hexlet.code.App;
import hexlet.code.BaseRepository;
import io.javalin.Javalin;
import io.javalin.testtools.JavalinTest;
import okhttp3.mockwebserver.MockResponse;
import okhttp3.mockwebserver.MockWebServer;
import okhttp3.mockwebserver.RecordedRequest;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.sql.SQLException;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

class AppTest {
    private static Javalin app;
    private static HikariDataSource dataSource;
    private static MockWebServer mockWebServer;
    private static String mockServerUrl;

    @BeforeAll
    static void beforeAll() throws IOException {
        mockWebServer = new MockWebServer();
        mockWebServer.start();
        mockServerUrl = mockWebServer.url("/").toString();

        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;");
        dataSource = new HikariDataSource(config);
        BaseRepository.dataSource = dataSource;

        initDatabase();
        app = App.getApp();
    }

    @AfterAll
    static void afterAll() throws IOException {
        if (dataSource != null) {
            dataSource.close();
        }
        if (app != null) {
            app.stop();
        }
        if (mockWebServer != null) {
            mockWebServer.shutdown();
        }
    }

    @BeforeEach
    void beforeEach() throws SQLException {
        try (var conn = dataSource.getConnection();
             var stmt = conn.createStatement()) {
            stmt.execute("DELETE FROM url_checks");
            stmt.execute("DELETE FROM urls");
            stmt.execute("ALTER TABLE urls ALTER COLUMN id RESTART WITH 1");
            stmt.execute("ALTER TABLE url_checks ALTER COLUMN id RESTART WITH 1");
        }
    }

    private static void initDatabase() {
        String createUrlsTable = """
            CREATE TABLE IF NOT EXISTS urls (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL UNIQUE,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """;

        String createChecksTable = """
            CREATE TABLE IF NOT EXISTS url_checks (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                url_id BIGINT NOT NULL REFERENCES urls(id) ON DELETE CASCADE,
                status_code INT,
                title VARCHAR(255),
                h1 VARCHAR(255),
                description TEXT,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """;

        try (var conn = dataSource.getConnection();
             var stmt = conn.createStatement()) {
            stmt.execute(createUrlsTable);
            stmt.execute(createChecksTable);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Test
    void testCheckUrlSuccess() throws SQLException, InterruptedException {
        String mockHtml = """
            <html>
                <head><title>Test Title</title></head>
                <body>
                    <h1>Test H1</h1>
                    <meta name="description" content="Test Description">
                </body>
            </html>
            """;

        MockResponse mockResponse = new MockResponse()
                .setResponseCode(200)
                .setBody(mockHtml)
                .addHeader("Content-Type", "text/html");
        mockWebServer.enqueue(mockResponse);

        String testUrl = mockServerUrl;
        long urlId;
        try (var conn = dataSource.getConnection();
             var stmt = conn.prepareStatement("INSERT INTO urls (name) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
            stmt.setString(1, testUrl);
            stmt.executeUpdate();
            var generatedKeys = stmt.getGeneratedKeys();
            generatedKeys.next();
            urlId = generatedKeys.getLong(1);
        }

        final long id = urlId;
        JavalinTest.test(app, (server, client) -> {
            try (var response = client.post("/urls/" + id + "/checks", "")) {
                assertThat(response.code()).isEqualTo(200);
                assertThat(response.header("Location")).isEqualTo("/urls/" + id);
            }
        });

        try (var conn = dataSource.getConnection();
             var stmt = conn.createStatement();
             var rs = stmt.executeQuery("SELECT * FROM url_checks WHERE url_id = " + urlId)) {
            assertThat(rs.next()).isTrue();
            assertThat(rs.getInt("status_code")).isEqualTo(200);
            assertThat(rs.getString("title")).isEqualTo("Test Title");
            assertThat(rs.getString("h1")).isEqualTo("Test H1");
            assertThat(rs.getString("description")).isEqualTo("Test Description");
        }

        RecordedRequest recordedRequest = mockWebServer.takeRequest();
        assertThat(recordedRequest.getPath()).isEqualTo("/");
    }

    @Test
    void testCheckUrlClientError() throws SQLException {
        MockResponse mockResponse = new MockResponse().setResponseCode(404);
        mockWebServer.enqueue(mockResponse);

        String testUrl = mockServerUrl;
        long urlId;
        try (var conn = dataSource.getConnection();
             var stmt = conn.prepareStatement("INSERT INTO urls (name) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
            stmt.setString(1, testUrl);
            stmt.executeUpdate();
            var generatedKeys = stmt.getGeneratedKeys();
            generatedKeys.next();
            urlId = generatedKeys.getLong(1);
        }

        final long id = urlId;
        JavalinTest.test(app, (server, client) -> {
            try (var response = client.post("/urls/" + id + "/checks", "")) {
                assertThat(response.code()).isEqualTo(200);
            }
        });

        try (var conn = dataSource.getConnection();
             var stmt = conn.createStatement();
             var rs = stmt.executeQuery("SELECT COUNT(*) FROM url_checks WHERE url_id = " + urlId)) {
            rs.next();
            assertThat(rs.getInt(1)).isZero();
        }
    }

    @Test
    void testCheckUrlTruncatesLongText() throws SQLException {
        String longText = "a".repeat(300);
        String truncatedText = "a".repeat(200) + "...";

        String mockHtml = """
            <html>
                <head><title>%s</title></head>
                <body>
                    <h1>%s</h1>
                    <meta name="description" content="%s">
                </body>
            </html>
            """.formatted(longText, longText, longText);

        MockResponse mockResponse = new MockResponse()
                .setResponseCode(200)
                .setBody(mockHtml);
        mockWebServer.enqueue(mockResponse);

        String testUrl = mockServerUrl;
        long urlId;
        try (var conn = dataSource.getConnection();
             var stmt = conn.prepareStatement("INSERT INTO urls (name) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
            stmt.setString(1, testUrl);
            stmt.executeUpdate();
            var generatedKeys = stmt.getGeneratedKeys();
            generatedKeys.next();
            urlId = generatedKeys.getLong(1);
        }

        final long id = urlId;
        JavalinTest.test(app, (server, client) -> {
            client.post("/urls/" + id + "/checks", "");
        });

        try (var conn = dataSource.getConnection();
             var stmt = conn.createStatement();
             var rs = stmt.executeQuery("SELECT * FROM url_checks WHERE url_id = " + urlId)) {
            assertThat(rs.next()).isTrue();
            assertThat(rs.getString("title")).isEqualTo(truncatedText);
            assertThat(rs.getString("h1")).isEqualTo(truncatedText);
            assertThat(rs.getString("description")).isEqualTo(truncatedText);
        }
    }

    @Test
    void testUrlPageShowsCheckTable() throws SQLException {
        long urlId;
        try (var conn = dataSource.getConnection();
             var stmt = conn.prepareStatement("INSERT INTO urls (name) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
            stmt.setString(1, "https://example.com");
            stmt.executeUpdate();
            var generatedKeys = stmt.getGeneratedKeys();
            generatedKeys.next();
            urlId = generatedKeys.getLong(1);
        }

        try (var conn = dataSource.getConnection();
             var stmt = conn.prepareStatement("""
                 INSERT INTO url_checks (url_id, status_code, title, h1, description) 
                 VALUES (?, ?, ?, ?, ?)
                 """)) {
            stmt.setLong(1, urlId);
            stmt.setInt(2, 200);
            stmt.setString(3, "Example Title");
            stmt.setString(4, "Example H1");
            stmt.setString(5, "Example Description");
            stmt.executeUpdate();
        }

        final long id = urlId;
        JavalinTest.test(app, (server, client) -> {
            try (var response = client.get("/urls/" + id)) {
                assertThat(response.code()).isEqualTo(200);
                String body = response.body().string();
                assertThat(body).contains("<form method=\"post\" action=\"/urls/" + id + "/checks\">");
                assertThat(body).contains("<input type=\"submit\" value=\"Запустить проверку\">");
                assertThat(body).contains("data-test=\"checks\"");
                assertThat(body).contains("Example Title");
                assertThat(body).contains("Example H1");
                assertThat(body).contains("200");
            }
        });
    }
}