import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import hexlet.code.App;
import hexlet.code.BaseRepository;
import io.javalin.Javalin;
import io.javalin.testtools.JavalinTest;
import okhttp3.Response;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.SQLException;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

class AppTest {

    private static Javalin app;
    private static HikariDataSource dataSource;

    @BeforeAll
    static void beforeAll() {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;");
        dataSource = new HikariDataSource(config);
        BaseRepository.dataSource = dataSource;

        initDatabase();
        app = App.getApp();
    }

    @AfterAll
    static void afterAll() {
        if (dataSource != null) {
            dataSource.close();
        }
        if (app != null) {
            app.stop();
        }
    }

    @BeforeEach
    void beforeEach() throws SQLException {
        // Очищаем таблицы перед каждым тестом
        try (var conn = dataSource.getConnection();
             var stmt = conn.createStatement()) {
            stmt.execute("DELETE FROM url_checks");
            stmt.execute("DELETE FROM urls");
            stmt.execute("ALTER TABLE urls ALTER COLUMN id RESTART WITH 1");
            stmt.execute("ALTER TABLE url_checks ALTER COLUMN id RESTART WITH 1");
        }
    }

    private static void initDatabase() {
        String createUrlsTable = """
            CREATE TABLE IF NOT EXISTS urls (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL UNIQUE,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """;

        String createChecksTable = """
            CREATE TABLE IF NOT EXISTS url_checks (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                url_id BIGINT NOT NULL REFERENCES urls(id) ON DELETE CASCADE,
                status_code INT,
                title VARCHAR(255),
                h1 VARCHAR(255),
                description TEXT,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """;

        try (var conn = dataSource.getConnection();
             var stmt = conn.createStatement()) {
            stmt.execute(createUrlsTable);
            stmt.execute(createChecksTable);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    @Test
    void testRoot() {
        JavalinTest.test(app, (server, client) -> {
            try (Response response = client.get("/")) {
                assertThat(response.code()).isEqualTo(200);
                assertThat(response.body().string()).contains("Анализатор страниц");
            }
        });
    }

    @Test
    void testGetUrls() {
        JavalinTest.test(app, (server, client) -> {
            try (Response response = client.get("/urls")) {
                assertThat(response.code()).isEqualTo(200);
                assertThat(response.body().string()).contains("Сайты");
                assertThat(response.body().string()).contains("data-test=\"urls\"");
            }
        });
    }

    @Test
    void testCreateUrlSuccess() throws SQLException {
        JavalinTest.test(app, (server, client) -> {
            try (Response response = client.post("/urls", "url=https://example.com")) {
                assertThat(response.code()).isEqualTo(200);
                String location = response.header("Location");
                assertThat(location).isNotNull();
                assertThat(location).matches("/urls/\\d+");
            }
            try (var conn = dataSource.getConnection();
                 var stmt = conn.createStatement();
                 var rs = stmt.executeQuery("SELECT * FROM urls WHERE name = 'https://example.com'")) {
                assertThat(rs.next()).isTrue();
                assertThat(rs.getString("name")).isEqualTo("https://example.com");
            }
        });
    }

    @Test
    void testCreateUrlWithPort() {
        JavalinTest.test(app, (server, client) -> {
            try (Response response = client.post("/urls", "url=https://example.com:8080/some/path")) {
                assertThat(response.code()).isEqualTo(200);
            }
            try (var conn = dataSource.getConnection();
                 var stmt = conn.createStatement();
                 var rs = stmt.executeQuery("SELECT * FROM urls WHERE name = 'https://example.com:8080'")) {
                assertThat(rs.next()).isTrue();
            }
        });
    }

    @Test
    void testCreateUrlDuplicate() {
        JavalinTest.test(app, (server, client) -> {
            try (Response response1 = client.post("/urls", "url=https://duplicate.com")) {
                assertThat(response1.code()).isEqualTo(200);
            }
            try (Response response2 = client.post("/urls", "url=https://duplicate.com")) {
                assertThat(response2.code()).isEqualTo(200);
                String location = response2.header("Location");
                assertThat(location).matches("/urls/\\d+");
            }
            try (var conn = dataSource.getConnection();
                 var stmt = conn.createStatement();
                 var rs = stmt.executeQuery("SELECT COUNT(*) FROM urls WHERE name = 'https://duplicate.com'")) {
                rs.next();
                assertThat(rs.getInt(1)).isEqualTo(1);
            }
        });
    }

    @Test
    void testCreateUrlInvalid() {
        JavalinTest.test(app, (server, client) -> {
            try (Response response = client.post("/urls", "url=not-a-valid-url")) {
                assertThat(response.code()).isEqualTo(422);
                assertThat(response.body().string()).contains("Некорректный URL");
            }
            try (var conn = dataSource.getConnection();
                 var stmt = conn.createStatement();
                 var rs = stmt.executeQuery("SELECT COUNT(*) FROM urls")) {
                rs.next();
                assertThat(rs.getInt(1)).isEqualTo(0);
            }
        });
    }

    @Test
    void testGetUrlById() throws SQLException {
        long id;
        try (var conn = dataSource.getConnection();
             var stmt = conn.prepareStatement("INSERT INTO urls (name) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
            stmt.setString(1, "https://test.com");
            stmt.executeUpdate();
            var generatedKeys = stmt.getGeneratedKeys();
            generatedKeys.next();
            id = generatedKeys.getLong(1);
        }

        final long urlId = id;
        JavalinTest.test(app, (server, client) -> {
            try (Response response = client.get("/urls/" + urlId)) {
                assertThat(response.code()).isEqualTo(200);
                String body = response.body().string();
                assertThat(body).contains("https://test.com");
                assertThat(body).contains("data-test=\"url\"");
                assertThat(body).contains("<form method=\"post\" action=\"/urls/" + urlId + "/checks\">");
                assertThat(body).contains("<input type=\"submit\" value=\"Запустить проверку\">");
            }
        });
    }

    @Test
    void testGetUrlNotFound() {
        JavalinTest.test(app, (server, client) -> {
            try (Response response = client.get("/urls/99999")) {
                assertThat(response.code()).isEqualTo(404);
            }
        });
    }

    @Test
    void testCreateCheck() throws SQLException {
        long urlId;
        try (var conn = dataSource.getConnection();
             var stmt = conn.prepareStatement("INSERT INTO urls (name) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
            stmt.setString(1, "https://example.com");
            stmt.executeUpdate();
            var generatedKeys = stmt.getGeneratedKeys();
            generatedKeys.next();
            urlId = generatedKeys.getLong(1);
        }

        final long id = urlId;
        JavalinTest.test(app, (server, client) -> {
            try (Response response = client.post("/urls/" + id + "/checks", "")) {
                assertThat(response.code()).isEqualTo(200);
                // Проверяем редирект обратно на страницу URL
                String location = response.header("Location");
                assertThat(location).isEqualTo("/urls/" + id);
            }
        });

        try (var conn = dataSource.getConnection();
             var stmt = conn.createStatement();
             var rs = stmt.executeQuery("SELECT * FROM url_checks WHERE url_id = " + urlId)) {
            assertThat(rs.next()).isTrue();
            assertThat(rs.getInt("status_code")).isEqualTo(200);
        }
    }

    @Test
    void testUrlPageShowsChecksTable() throws SQLException {
        // Добавляем URL
        long urlId;
        try (var conn = dataSource.getConnection();
             var stmt = conn.prepareStatement("INSERT INTO urls (name) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
            stmt.setString(1, "https://example.com");
            stmt.executeUpdate();
            var generatedKeys = stmt.getGeneratedKeys();
            generatedKeys.next();
            urlId = generatedKeys.getLong(1);
        }
        try (var conn = dataSource.getConnection();
             var stmt = conn.prepareStatement("""
                 INSERT INTO url_checks (url_id, status_code, title, h1, description) 
                 VALUES (?, ?, ?, ?, ?)
                 """)) {
            stmt.setLong(1, urlId);
            stmt.setInt(2, 200);
            stmt.setString(3, "Example Title");
            stmt.setString(4, "Example H1");
            stmt.setString(5, "Example Description");
            stmt.executeUpdate();
        }

        final long id = urlId;
        JavalinTest.test(app, (server, client) -> {
            try (Response response = client.get("/urls/" + id)) {
                assertThat(response.code()).isEqualTo(200);
                String body = response.body().string();
                // Проверяем наличие таблицы с проверками
                assertThat(body).contains("data-test=\"checks\"");
                // Проверяем содержимое проверки
                assertThat(body).contains("Example Title");
                assertThat(body).contains("Example H1");
                assertThat(body).contains("Example Description");
                assertThat(body).contains("200");
            }
        });
    }

    @Test
    void testUrlsPageShowsLastCheckCode() throws SQLException {
        long urlId;
        try (var conn = dataSource.getConnection();
             var stmt = conn.prepareStatement("INSERT INTO urls (name) VALUES (?)", Statement.RETURN_GENERATED_KEYS)) {
            stmt.setString(1, "https://example.com");
            stmt.executeUpdate();
            var generatedKeys = stmt.getGeneratedKeys();
            generatedKeys.next();
            urlId = generatedKeys.getLong(1);
        }
        try (var conn = dataSource.getConnection();
             var stmt = conn.prepareStatement("INSERT INTO url_checks (url_id, status_code) VALUES (?, ?)")) {
            stmt.setLong(1, urlId);
            stmt.setInt(2, 200);
            stmt.executeUpdate();
        }

        JavalinTest.test(app, (server, client) -> {
            try (Response response = client.get("/urls")) {
                assertThat(response.code()).isEqualTo(200);
                String body = response.body().string();
                assertThat(body).contains("data-test=\"urls\"");
                assertThat(body).contains("200");
            }
        });
    }

    @Test
    void testUrlsSortedByIdDesc() throws SQLException {
        try (var conn = dataSource.getConnection();
             var stmt = conn.prepareStatement("INSERT INTO urls (name) VALUES (?)")) {
            stmt.setString(1, "https://first.com");
            stmt.executeUpdate();
            stmt.setString(1, "https://second.com");
            stmt.executeUpdate();
            stmt.setString(1, "https://third.com");
            stmt.executeUpdate();
        }

        JavalinTest.test(app, (server, client) -> {
            try (Response response = client.get("/urls")) {
                assertThat(response.code()).isEqualTo(200);
                String body = response.body().string();

                int thirdIndex = body.indexOf("https://third.com");
                int secondIndex = body.indexOf("https://second.com");
                int firstIndex = body.indexOf("https://first.com");

                assertThat(thirdIndex).isLessThan(secondIndex);
                assertThat(secondIndex).isLessThan(firstIndex);
            }
        });
    }

    @Test
    void testFlashMessageOnSuccess() {
        JavalinTest.test(app, (server, client) -> {
            try (Response response = client.post("/urls", "url=https://flash-success.com")) {
                assertThat(response.code()).isEqualTo(200);
                String location = response.header("Location");
                assertThat(location).matches("/urls/\\d+");
            }
        });
    }

    @Test
    void testFlashMessageOnDuplicate() {
        JavalinTest.test(app, (server, client) -> {
            client.post("/urls", "url=https://flash-duplicate.com");

            try (Response response = client.post("/urls", "url=https://flash-duplicate.com")) {
                assertThat(response.code()).isEqualTo(200);
                String location = response.header("Location");
                assertThat(location).matches("/urls/\\d+");
            }
        });
    }

    @Test
    void testFlashMessageOnInvalidUrl() {
        JavalinTest.test(app, (server, client) -> {
            try (Response response = client.post("/urls", "url=invalid")) {
                assertThat(response.code()).isEqualTo(422);
                assertThat(response.body().string()).contains("Некорректный URL");
            }
        });
    }
}